config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])

    render :new
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to home_path, notice: "The post has been successfully updated"
    else
      render :new
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to home_path, notice: "The post has been successfully created"
    else
      render :new
    end
  end

  def destroy
    Post.find(params[:id]).destroy!

    redirect_to home_path, notice: "The post has been successfully removed"
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Press+Start+2P' %>
    <%= stylesheet_link_tag 'https://unpkg.com/nes.css@latest/css/nes.min.css' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/notifications' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post_path(post.id) do %>
    <div class="nes-container with-title">
      <p class="title nes-text is-success"><%= post.title %></p>
      <p><%= post.body %></p>
    </div>
  <% end %>
  <br>
<% end %>

app/views/posts/new.html.erb
<% if @post.errors.present? %>
	<div class="nes-container is-dark">
		<ul class="nes-list is-disc nes-text is-error">
		<% @post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	</div>
	<br><br>
<% end %>

<%= form_for @post, url: polymorphic_path(@post), validate: true do |f| %>

	<div class='nes-field'>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'nes-input' %>
	</div>
	<br>
	<div class='nes-field'>
		<%= f.label :body %>
		<%= f.text_area :body, class: 'nes-textarea'%>
	</div>
	<br>
	<%= link_to('Back', @post.new_record? ? home_path : post_path(@post.id), class: 'nes-btn') %>
	<%= f.submit class: 'nes-btn is-success' %>

<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h1>
<br>
<div class="nes-container is-rounded">
  <p><%= @post.body %></p>
</div>
<br>
<%= link_to 'Back', home_path, class: 'nes-btn' %>
<%= link_to 'Edit', edit_post_path(@post.id), class: 'nes-btn is-primary' %>
<br><br>
<%= button_to 'Remove', post_path(@post.id), method: :delete, class: 'nes-btn is-error' %>

app/views/shared/_header.html.erb
<div style="display: flex; align-items: center; height: 75px;" class="container">
<%= link_to home_path do %>
  <h1>SimpleBlog</h1>
<% end %>
<%= link_to new_post_path do %>
  <button class="nes-btn is-primary">Add New Post</button>
<% end %>
</div>
<hr style="margin-top: 0;">
<br><br>

app/views/shared/_notifications.html.erb
<% if notice.present? %>
  <div class="container">
    <div class="nes-container is-dark">
      <p class="nes-text is-success"><%= notice %></p>
    </div>
  </div>
  <br><br>
<% end %>